# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zpool/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zpool/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "zpool/var";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4966-376F";
      fsType = "vfat";
    };

  fileSystems."/data" =
    { device = "datapool";
      fsType = "zfs";
    };

  fileSystems."/data/media" =
    { device = "datapool/media";
      fsType = "zfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.config.packageOverrides = pkgs: {
	vaapiIntel = pkgs.vaapiIntel.override { enableHybridCodec = true; };
  	jellyfin-ffmpeg = pkgs.jellyfin-ffmpeg.override {
		ffmpeg_6-full = pkgs.ffmpeg_6-full.override {
			withMfx = false;
			withVpl = true;
		};
	};
  };

  hardware.opengl = {
	enable = true;
	extraPackages = with pkgs; [
		intel-media-driver
		vaapiVdpau
		intel-compute-runtime
		onevpl-intel-gpu
	];
  };

  environment.sessionVariables = { LIBVA_DRIVER_NAME = "iHD"; };
  
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
